### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by Nicetypeplayer** [lizhaoliu-Lec/CNLE#2]
url = ('https://www.logos.t.u-tokyo.ac.jp/~hassy/publications/arxiv2016jmt/'
           'jmt_pre-trained_embeddings.tar.gz')
Has this URL changed? I can't open it

**Comment by Nicetypeplayer** [comment]
If anyone knows, please let me know how to fix it, thanks

**Comment by lizhaoliu-Lec** [comment]
Yes. I can not access it through web browser either. 
But I am downloading it through xunlei app with the same URL ``http://www.logos.t.u-tokyo.ac.jp/~hassy/publications/arxiv2016jmt/jmt_pre-trained_embeddings.tar.gz``. 
If you need it, I can send the downloaded file via eamil.
![image](https://user-images.githubusercontent.com/38394970/227758802-35287f5c-a5fb-4b10-b76c-481237af854c.png)

**Comment by Nicetypeplayer** [comment]
> Yes. I can not access it through web browser either. But I am downloading it through xunlei app with the same URL `http://www.logos.t.u-tokyo.ac.jp/~hassy/publications/arxiv2016jmt/jmt_pre-trained_embeddings.tar.gz`. If you need it, I can send the downloaded file via eamil. ![image](https://user-images.githubusercontent.com/38394970/227758802-35287f5c-a5fb-4b10-b76c-481237af854c.png)

OK, I see that Xunlei can be downloaded, I will download it myself, thank you very much
