### ISSUE TITLE
 CharNGram is 404 Not Found

### ISSUE THREAD

**Issue by mihua5329** [lizhaoliu-Lec/CNLE#3]
Hello,
The site of CharNGram is 404 Not Found.
Could you please provide the jmt_pre-trained_embeddings.tar.gz ? 2350321824@qq.com

Thank you very much!

**Comment by lizhaoliu-Lec** [comment]
Yes. I have sent the file. Please check the email.

**Comment by mihua5329** [comment]
Thanks very much for your reply.
An error occurred when `python train.py --train_tasks schema --device 0 --embeddings embedding_path`. 

>     l2i_dict = val_task2dict[args.val_tasks[0]]  KeyError: 'schema'
could you please provide the processed Reuters data or a preprocessing script that converts the downloaded raw data Reuters into the json file used in your experimence?
This will provide a great help.

**Comment by lizhaoliu-Lec** [comment]
The code is pretty old to me.

1. For error `l2i_dict = val_task2dict[args.val_tasks[0]]  KeyError: 'schema'`, make sure the `schema` folder containing the {train,validation,test}.jsonl is under `.data/my_custom_dataset`.
2. For preprocessing script that converts the raw Reuters data into jsonl, the related scripts are left on my old labtop. I will upload it to this repo ASAP (before 5.1). Just saying, it will be more convenient for you just write the script directly following the schema dataset format: 
- a reuters folder containing {train,validation,test}.jsonl corresponding to train/val/test split (val and test can be the same)
- for each line in the jsonl file: {"context": "The text to classify", "question": "All labels for reuters dataset (81 labels as I can recall?)", "answer": "Multi lables for the context"}.
- all question are the same: white space seperated labels of the dataset

**Comment by mihua5329** [comment]
Thank you for your sharing.
