### ISSUE TITLE
请问哪个是你的模型

### ISSUE THREAD

**Issue by JNU-luyi** [lizhaoliu-Lec/CNLE#4]
![image](https://github.com/lizhaoliu-Lec/CNLE/assets/100257990/b1a3d3c0-68f2-494d-bc95-f6d3db59f420)
刚刚接触NLP 请问你是在decanlp 的项目基础上增加的代码吗  哪个是你的模型

**Comment by lizhaoliu-Lec** [comment]
![image](https://github.com/lizhaoliu-Lec/CNLE/assets/38394970/01603415-9ab8-4373-b2e2-e3bc8e01bbaf)
dien.py

**Comment by JNU-luyi** [comment]
thanks my bro 谢谢大哥！！！！！

**Comment by JNU-luyi** [comment]
您好，看了很久，还是没有跑起来方便 细聊一下吗 通过邮箱或者其他方式都可以 。万分感谢！

**Comment by JNU-luyi** [comment]
![image](https://github.com/lizhaoliu-Lec/CNLE/assets/100257990/1c93ee59-90ab-4bd2-8778-001826db75ab)

**Comment by lizhaoliu-Lec** [comment]
charNGram 是否正确下载？可以用迅雷下载

**Comment by lizhaoliu-Lec** [comment]
feel free to contact me via email 2524463910@qq.com
可以通过邮箱 2524463910@qq.com 和我交流~

**Comment by Wink-L** [comment]
您好，请教一下这个charNGram的下载地址。
我不知道是哪里出了错？
![image](https://github.com/lizhaoliu-Lec/CNLE/assets/79886948/653f2518-49c5-48f1-9e8a-bd3d1426556b)

**Comment by lizhaoliu-Lec** [comment]
https://www.logos.t.u-tokyo.ac.jp/~hassy/publications/arxiv2016jmt/jmt_pre-trained_embeddings.tar.gz
使用迅雷下载该链接即可

**Comment by Wink-L** [comment]
File "/root/autodl-tmp/CNLE/metrics.py", line 348, in compute_multi_ones_hot_vector
    l2i_dict = val_task2dict[args.val_tasks[0]]
KeyError: 'schema'
师兄，这个错是因为什么呢，我一直解决不了，没太明白哪里出了问题。能提供一些建议嘛，感谢！

**Comment by Wink-L** [comment]
上边问题我解决了，我想问一下，这个模型训练的时候没有设置epoch嘛，怎么一直不停的iteration呢？也没看到trian的batch_size大小，就这两个问题，感谢！
